language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: deploy
      if: branch = dev
      install:
        - apt-get update -qq
        - 'which ssh-agent || ( apt-get install -qq openssh-client )'
        - eval $(ssh-agent -s)
        - ssh-add <(echo $SSH_PRIVATE_KEY_DEV)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts  
        - npm i
      script: ./CI/deploy-dev.sh

