language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: deploy
      if: branch = dev
      install:
        # Decrypt the git_deploy_key.enc key into /tmp/monitoolbackdev
        - openssl aes-256-cbc -K $encrypted_d826e144b0a2_key -iv $encrypted_d826e144b0a2_iv -in keys/monitoolbackdev.enc -out /tmp/monitoolbackdev -d
        # Make sure only the current user can read the private key
        - chmod 600 /tmp/monitoolbackdev
        # Create a script to return the passphrase environment variable to ssh-add
        - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
        # Start the authentication agent
        - eval "$(ssh-agent -s)"
        # Add the key to the authentication agent
        - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/monitoolbackdev </dev/null
      script: ./CI/deploy-dev.sh /tmp/monitoolbackdev
    - stage: deploy
      if: branch = uat
      install:
        # Decrypt the git_deploy_key.enc key into /tmp/monitoolbackuat
        - openssl aes-256-cbc -K $encrypted_4ee49d49f72a_key -iv $encrypted_4ee49d49f72a_iv -in keys/monitoolbackuat.enc -out /tmp/monitoolbackuat -d
        # Make sure only the current user can read the private key
        - chmod 600 /tmp/monitoolbackuat
        # Create a script to return the passphrase environment variable to ssh-add
        - echo 'echo ${SSH_PASSPHRASE_UAT}' > /tmp/askpass && chmod +x /tmp/askpass
        # Start the authentication agent
        - eval "$(ssh-agent -s)"
        # Add the key to the authentication agent
        - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/monitoolbackuat </dev/null
      script: ./CI/deploy-uat.sh /tmp/monitoolbackuat
    - stage: deploy
      if: branch = master
      install:
        # Decrypt the git_deploy_key.enc key into /tmp/monitoolbackuat
        - openssl aes-256-cbc -K $encrypted_bea0181439c1_key -iv $encrypted_bea0181439c1_iv -in keys/monitoolbackprod.enc -out /tmp/monitoolbackprod -d
        # Make sure only the current user can read the private key
        - chmod 600 /tmp/monitoolbackprod
        # Create a script to return the passphrase environment variable to ssh-add
        - echo 'echo ${SSH_PASSPHRASE_PROD}' > /tmp/askpass && chmod +x /tmp/askpass
        # Start the authentication agent
        - eval "$(ssh-agent -s)"
        # Add the key to the authentication agent
        - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/monitoolbackprod </dev/null
      script: ./CI/deploy-prod.sh /tmp/monitoolbackprod

