language: node_js
node_js:
  - 10

jobs:
  include:
    - stage: deploy
      if: branch = dev
      install:
        # Decrypt the git_deploy_key.enc key into /tmp/monitoolbackdev
        - openssl aes-256-cbc -K $encrypted_d826e144b0a2_key -iv $encrypted_d826e144b0a2_iv -in monitoolbackdev.enc -out /tmp/monitoolbackdev -d
        # Make sure only the current user can read the private key
        - chmod 600 /tmp/monitoolbackdev
        # Create a script to return the passphrase environment variable to ssh-add
        - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
        # Start the authentication agent
        - eval "$(ssh-agent -s)"
        # Add the key to the authentication agent
        - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/monitoolbackdev </dev/null
      script: ./CI/deploy-dev.sh /tmp/monitoolbackdev SSH_ASKPASS

