version: "3.6"

services:

  reverse_proxy:
    image: fholzer/nginx-brotli
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro

  frontend_watch:
    image: node:8
    working_dir: /app
    command: sh -c "yarn install --frozen-lockfile && yarn run watch"
    volumes:
      - ../frontend/src:/app/src:ro
      - ../frontend/package.json:/app/package.json
      - ../frontend/webpack.config.js:/app/webpack.config.js:ro
      - ../frontend/yarn.lock:/app/yarn.lock
      - frontend_dist:/app/dist
      - frontend_node_modules:/app/node_modules

  api:
    image: node:10
    working_dir: /app
    command: sh -c "yarn install --frozen-lockfile && yarn run start"
    ports:
      - "9229:9229" # debugger
    volumes:
      - ../api/lib:/app/lib:ro
      - ../api/package.json:/app/package.json:ro
      - ../api/yarn.lock:/app/yarn.lock:ro
      - api_node_modules:/app/node_modules
    environment:
      MONITOOL_DEBUG: "TRUE"
      MONITOOL_PORT: "80"
      MONITOOL_COOKIE_SECRET: "123456789"
      MONITOOL_COUCHDB_HOST: "couchdb"
      MONITOOL_API_GOOGLE_FILE: "/var/run/secrets/googletranslate_apikey"
      MONITOOL_AUTH_ADMINISTRATOR: "training"
      MONITOOL_AUTH_PROVIDERS_AZUREAD: "FALSE"
      MONITOOL_AUTH_PROVIDERS_TRAINING: "TRUE"
      MONITOOL_AUTH_PROVIDERS_TRAINING_ACCOUNT: "training"
    secrets:
      - googletranslate_apikey

  couchdb:
    image: couchdb:latest
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: ""
    volumes:
      - couchdb_data:/opt/couchdb/data

secrets:
  googletranslate_apikey:
    external: true

volumes:
  api_node_modules:
  couchdb_data:
  frontend_dist:
  frontend_node_modules:
