version: "3.6"

services:

  reverse_proxy:
    image: romaingilliotte/monitool-frontend:latest
    networks:
      - frontend
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    image: romaingilliotte/monitool-api:latest
    networks:
      - backend
      - frontend
    depends_on:
      - couchdb
    environment:
      MONITOOL_DEBUG: "FALSE"
      MONITOOL_PORT: "80"
      MONITOOL_COOKIE_SECRET: "123456789"
      MONITOOL_COUCHDB_HOST: "couchdb"
      MONITOOL_API_GOOGLE_FILE: "/var/run/secrets/googletranslate_apikey"
      MONITOOL_AUTH_ADMINISTRATOR: "training"
      MONITOOL_AUTH_PROVIDERS_AZUREAD: "FALSE"
      MONITOOL_AUTH_PROVIDERS_TRAINING: "TRUE"
      MONITOOL_AUTH_PROVIDERS_TRAINING_ACCOUNT: "training"
    secrets:
      - googletranslate_apikey

  couchdb:
    image: couchdb:1
    networks:
      - backend
    volumes:
      - couchdb-data:/usr/local/var/lib/couchdb

networks:
  frontend:
  backend:

secrets:
  googletranslate_apikey:
    external: true

volumes:
  couchdb-data:
