version: "3.6"

services:

  reverse_proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend_watch
      - api

  frontend_watch:
    image: node:8
    working_dir: /app
    command: sh -c "yarn install && yarn run build && yarn run watch"
    volumes:
      - ../frontend:/app
      - frontend_dist:/app/dist
      - frontend_node_modules:/app/node_modules

  api:
    image: node:8
    working_dir: /app

    # Give 5 seconds for couchdb to start
    command: sh -c "yarn install && sleep 5 && yarn run start"
    volumes:
      - ../api:/app
      - api_node_modules:/app/node_modules
    depends_on:
      - couchdb
    environment:
      MONITOOL_DEBUG: "TRUE"
      MONITOOL_PORT: "80"
      MONITOOL_COOKIE_SECRET: "123456789"
      MONITOOL_COUCHDB_HOST: "couchdb"
      MONITOOL_API_GOOGLE_FILE: "/var/run/secrets/googletranslate_apikey"
      MONITOOL_AUTH_ADMINISTRATOR: "training"
      MONITOOL_AUTH_PROVIDERS_AZUREAD: "FALSE"
      MONITOOL_AUTH_PROVIDERS_TRAINING: "TRUE"
      MONITOOL_AUTH_PROVIDERS_TRAINING_ACCOUNT: "training"
    secrets:
      - googletranslate_apikey

  couchdb:
    image: couchdb:1
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: ""
    volumes:
      - couchdb_data:/usr/local/var/lib/couchdb

secrets:
  googletranslate_apikey:
    external: true

volumes:
  api_node_modules:
  couchdb_data:
  frontend_dist:
  frontend_node_modules:
