version: "3.6"

services:

  reverse_proxy:
    image: fholzer/nginx-brotli:v1.15.8
    restart: always
    ports:
      - "8045:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  api:
    image: node:10
    working_dir: /app
    restart: always
    command: sh -c "yarn install --frozen-lockfile && yarn run start"
    ports:
      - "9229:9229" # debugger
    volumes:
      - ../api/lib:/app/lib:ro
      - ../api/package.json:/app/package.json:ro
      - ../api/yarn.lock:/app/yarn.lock:ro
      - api_node_modules:/app/node_modules
    environment:
      MONITOOL_DEBUG: "TRUE"
      MONITOOL_PORT: "80"
      MONITOOL_COOKIE_SECRET: "123456789"
      MONITOOL_COUCHDB_HOST: "couchdb"
      MONITOOL_COUCHDB_USER: "admin"
      MONITOOL_COUCHDB_PASS: "admin"
      MONITOOL_AUTH_ADMINISTRATOR: "training"
      MONITOOL_AUTH_PROVIDERS_AZUREAD: "FALSE"
      MONITOOL_AUTH_PROVIDERS_TRAINING: "TRUE"
      MONITOOL_AUTH_PROVIDERS_TRAINING_ACCOUNT: "training"

  couchdb:
    image: couchdb:2
    restart: always
    ports:
      - "5984:5984"
    environment:
      COUCHDB_USER: "admin"
      COUCHDB_PASSWORD: ""
    volumes:
      - ../couchdb_data:/opt/couchdb/data

volumes:
  api_node_modules:
  couchdb_data:
  frontend_dist:
  frontend_node_modules:
